CREATE TABLE CLOTHING_BRAND(
    brand_id INT PRIMARY KEY NOT NULL,
    name VARCHAR(45)
)

INSERT INTO `clothing_brand`(`brand_id`, `name`) VALUES (1,'GAP');
INSERT INTO `clothing_brand`(`brand_id`, `name`) VALUES (2,'POLO RALPH LAUREN');
INSERT INTO `clothing_brand`(`brand_id`, `name`) VALUES (3,'MNG');
INSERT INTO `clothing_brand`(`brand_id`, `name`) VALUES (4,'DEREK');
INSERT INTO `clothing_brand`(`brand_id`, `name`) VALUES (5,'CROYDON');
INSERT INTO `clothing_brand`(`brand_id`, `name`) VALUES (6,'ADN');
INSERT INTO `clothing_brand`(`brand_id`, `name`) VALUES (7,'APOLOGY');
INSERT INTO `clothing_brand`(`brand_id`, `name`) VALUES (8,'FILA');
INSERT INTO `clothing_brand`(`brand_id`, `name`) VALUES (9,'LEVIS');
INSERT INTO `clothing_brand`(`brand_id`, `name`) VALUES (10,'CALVIN KLEIN');
INSERT INTO `clothing_brand`(`brand_id`, `name`) VALUES (11,'TOMMY HILFIGER');